export let BillingData = [
  {
    BillNo: 1456,
    CustomerName: 'soorya',
    Items: 5,
    status: 'pending',
    Price: 255,
  },
  {
    BillNo: 1457,
    CustomerName: 'john',
    Items: 3,
    status: 'Paid',
    Price: 150,
  },
  {
    BillNo: 1458,
    CustomerName: 'emma',
    Items: 2,
    status: 'Unpaid',
    Price: 90,
  },
  {
    BillNo: 1459,
    CustomerName: 'alex',
    Items: 7,
    status: 'pending',
    Price: 400,
  },
  {
    BillNo: 1460,
    CustomerName: 'sara',
    Items: 4,
    status: 'Paid',
    Price: 200,
  },
  {
    BillNo: 1461,
    CustomerName: 'mike',
    Items: 6,
    status: 'Unpaid',
    Price: 300,
  },
  {
    BillNo: 1462,
    CustomerName: 'lisa',
    Items: 3,
    status: 'pending',
    Price: 150,
  },
  {
    BillNo: 1463,
    CustomerName: 'ryan',
    Items: 2,
    status: 'pending',
    Price: 90,
  },
  {
    BillNo: 1464,
    CustomerName: 'jessica',
    Items: 8,
    status: 'pending',
    Price: 450,
  },
  {
    BillNo: 1465,
    CustomerName: 'david',
    Items: 1,
    status: 'pending',
    Price: 50,
  },
  {
    BillNo: 1466,
    CustomerName: 'emily',
    Items: 9,
    status: 'pending',
    Price: 500,
  },
  {
    BillNo: 1467,
    CustomerName: 'chris',
    Items: 3,
    status: 'pending',
    Price: 150,
  },
  {
    BillNo: 1468,
    CustomerName: 'amy',
    Items: 5,
    status: 'pending',
    Price: 255,
  },
  {
    BillNo: 1469,
    CustomerName: 'matt',
    Items: 4,
    status: 'pending',
    Price: 200,
  },
  {
    BillNo: 1470,
    CustomerName: 'jennifer',
    Items: 6,
    status: 'pending',
    Price: 300,
  },
  {
    BillNo: 1471,
    CustomerName: 'kevin',
    Items: 2,
    status: 'pending',
    Price: 90,
  },
  {
    BillNo: 1472,
    CustomerName: 'amanda',
    Items: 7,
    status: 'pending',
    Price: 400,
  },
  {
    BillNo: 1473,
    CustomerName: 'justin',
    Items: 3,
    status: 'pending',
    Price: 150,
  },
  {
    BillNo: 1474,
    CustomerName: 'natalie',
    Items: 5,
    status: 'pending',
    Price: 255,
  },
  {
    BillNo: 1475,
    CustomerName: 'brandon',
    Items: 4,
    status: 'pending',
    Price: 200,
  },
  {
    BillNo: 1476,
    CustomerName: 'stephanie',
    Items: 6,
    status: 'pending',
    Price: 300,
  },
  {
    BillNo: 1477,
    CustomerName: 'mark',
    Items: 2,
    status: 'pending',
    Price: 90,
  },
  {
    BillNo: 1478,
    CustomerName: 'rachel',
    Items: 7,
    status: 'pending',
    Price: 400,
  },
  {
    BillNo: 1479,
    CustomerName: 'jason',
    Items: 3,
    status: 'pending',
    Price: 150,
  },
  {
    BillNo: 1480,
    CustomerName: 'samantha',
    Items: 5,
    status: 'pending',
    Price: 255,
  },
  {
    BillNo: 1481,
    CustomerName: 'eric',
    Items: 4,
    status: 'pending',
    Price: 200,
  },
  {
    BillNo: 1482,
    CustomerName: 'katie',
    Items: 6,
    status: 'pending',
    Price: 300,
  },
  {
    BillNo: 1483,
    CustomerName: 'brian',
    Items: 2,
    status: 'pending',
    Price: 90,
  },
  {
    BillNo: 1484,
    CustomerName: 'julia',
    Items: 7,
    status: 'pending',
    Price: 400,
  },
  {
    BillNo: 1485,
    CustomerName: 'nathan',
    Items: 3,
    status: 'pending',
    Price: 150,
  }
];
