export let BillMockData = [
    {
      id:1,
      itemName:"tomato",
      price:1,
      quantity:5,
      totalPrice:50
    },
    {
        id:2,
      itemName:"potato",
      price:10,
      quantity:15,
      totalPrice:50
    },
    {
        id:3,
      itemName:"onion",
      price:14,
      quantity:52,
      totalPrice:150
    },
    {
        id:4,
      itemName:"carror",
      price:14,
      quantity:12,
      totalPrice:500
    },
    {
        id:5,
      itemName:"bins",
      price:11,
      quantity:75,
      totalPrice:250
    },
    {
        id:6,
      itemName:"banana",
      price:12,
      quantity:51,
      totalPrice:250
    },
    {
        id:7,
      itemName:"apple",
      price:11,
      quantity:51,
      totalPrice:650
    },
    {
        id:8,
      itemName:"orange",
      price:1,
      quantity:5,
      totalPrice:50
    },
    {
        id:9,
      itemName:"carror",
      price:12,
      quantity:59,
      totalPrice:520
    },
    {
        id:10,
      itemName:"brinjal",
      price:19,
      quantity:56,
      totalPrice:50
    },
]