export let CustomerList = [
    {
      Id: 1,
      CustomerName: 'Soorya',
      CustomerNumber: 9456874541,
      IsActive: true,
      CustomerEmail: 'soorya147@gmail.com',
    },
    {
      Id: 2,
      CustomerName: 'John Doe',
      CustomerNumber: 9876543210,
      IsActive: true,
      CustomerEmail: 'johndoe@example.com',
    },
    {
      Id: 3,
      CustomerName: 'Jane Smith',
      CustomerNumber: 8765432109,
      IsActive: false,
      CustomerEmail: 'janesmith@example.com',
    },
    {
      Id: 4,
      CustomerName: 'Michael Johnson',
      CustomerNumber: 7654321098,
      IsActive: true,
      CustomerEmail: 'michaeljohnson@example.com',
    },
    {
      Id: 5,
      CustomerName: 'Emily Brown',
      CustomerNumber: 6543210987,
      IsActive: true,
      CustomerEmail: 'emilybrown@example.com',
    },
    {
      Id: 6,
      CustomerName: 'David Lee',
      CustomerNumber: 5432109876,
      IsActive: false,
      CustomerEmail: 'davidlee@example.com',
    },
    {
      Id: 7,
      CustomerName: 'Sarah Wilson',
      CustomerNumber: 4321098765,
      IsActive: true,
      CustomerEmail: 'sarahwilson@example.com',
    },
    {
      Id: 8,
      CustomerName: 'Chris Taylor',
      CustomerNumber: 3210987654,
      IsActive: true,
      CustomerEmail: 'christaylor@example.com',
    },
    {
      Id: 9,
      CustomerName: 'Jessica Martinez',
      CustomerNumber: 2109876543,
      IsActive: false,
      CustomerEmail: 'jessicamartinez@example.com',
    },
    {
      Id: 10,
      CustomerName: 'Kevin Garcia',
      CustomerNumber: 1098765432,
      IsActive: true,
      CustomerEmail: 'kevingarcia@example.com',
    },
    {
      Id: 11,
      CustomerName: 'Amanda Thomas',
      CustomerNumber: 9876543211,
      IsActive: true,
      CustomerEmail: 'amandathomas@example.com',
    },
    {
      Id: 12,
      CustomerName: 'Matthew Hernandez',
      CustomerNumber: 8765432101,
      IsActive: false,
      CustomerEmail: 'matthewhernandez@example.com',
    },
    {
      Id: 13,
      CustomerName: 'Ashley Nguyen',
      CustomerNumber: 7654321090,
      IsActive: true,
      CustomerEmail: 'ashleynguyen@example.com',
    },
    {
      Id: 14,
      CustomerName: 'Ryan King',
      CustomerNumber: 6543210989,
      IsActive: true,
      CustomerEmail: 'ryanking@example.com',
    },
    {
      Id: 15,
      CustomerName: 'Melissa Lopez',
      CustomerNumber: 5432109878,
      IsActive: false,
      CustomerEmail: 'melissalopez@example.com',
    },
    {
      Id: 16,
      CustomerName: 'Justin Hill',
      CustomerNumber: 4321098767,
      IsActive: true,
      CustomerEmail: 'justinhill@example.com',
    },
    {
      Id: 17,
      CustomerName: 'Stephanie Scott',
      CustomerNumber: 3210987656,
      IsActive: true,
      CustomerEmail: 'stephaniescott@example.com',
    },
    {
      Id: 18,
      CustomerName: 'Erica Green',
      CustomerNumber: 2109876545,
      IsActive: false,
      CustomerEmail: 'ericagreen@example.com',
    },
    {
      Id: 19,
      CustomerName: 'Brian Martinez',
      CustomerNumber: 1098765434,
      IsActive: true,
      CustomerEmail: 'brianmartinez@example.com',
    },
    {
      Id: 20,
      CustomerName: 'Catherine Allen',
      CustomerNumber: 9876543233,
      IsActive: true,
      CustomerEmail: 'catherineallen@example.com',
    },
    {
      Id: 21,
      CustomerName: 'Nicholas Rodriguez',
      CustomerNumber: 8765432122,
      IsActive: false,
      CustomerEmail: 'nicholasrodriguez@example.com',
    },
    {
      Id: 22,
      CustomerName: 'Christina Hill',
      CustomerNumber: 7654321111,
      IsActive: true,
      CustomerEmail: 'christinahill@example.com',
    },
    {
      Id: 23,
      CustomerName: 'Brandon Davis',
      CustomerNumber: 6543211000,
      IsActive: true,
      CustomerEmail: 'brandondavis@example.com',
    },
    {
      Id: 24,
      CustomerName: 'Rachel Martinez',
      CustomerNumber: 5432109899,
      IsActive: false,
      CustomerEmail: 'rachelmartinez@example.com',
    },
    {
      Id: 25,
      CustomerName: 'Patrick Turner',
      CustomerNumber: 4321098788,
      IsActive: true,
      CustomerEmail: 'patrickturner@example.com',
    },
    {
      Id: 26,
      CustomerName: 'Samantha Brown',
      CustomerNumber: 3210987677,
      IsActive: true,
      CustomerEmail: 'samanthabrown@example.com',
    },
    {
      Id: 27,
      CustomerName: 'Gregory White',
      CustomerNumber: 2109876566,
      IsActive: false,
      CustomerEmail: 'gregorywhite@example.com',
    },
    {
      Id: 28,
      CustomerName: 'Amy Scott',
      CustomerNumber: 1098765455,
      IsActive: true,
      CustomerEmail: 'amyscott@example.com',
    },
    {
      Id: 29,
      CustomerName: 'Jeffrey Harris',
      CustomerNumber: 9876543344,
      IsActive: true,
      CustomerEmail: 'jeffreyharris@example.com',
    },
    {
      Id: 30,
      CustomerName: 'Hannah Turner',
      CustomerNumber: 8765432233,
      IsActive: false,
      CustomerEmail: 'hannahturner@example.com',
    },
  ];
  